name: Release Letter

on: [workflow_dispatch]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build:release

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          useGitmojis: false
          reverseOrder: false
          excludeTypes: build,docs,style,chore
          includeInvalidCommits: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: Zip Letter production files
        run: zip -r letter.zip dist/

      - name: Upload Letter artifacts
        uses: actions/upload-artifact@v3
        with:
          name: letter
          path: letter.zip

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          generateReleaseNotes: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          artifacts: "letter.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: Update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
